#version: '2'
version: '3.7'

volumes:
  nextcloud:
  db:

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "9000:9000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/web/docker/portainer/data:/data

  db:
#    image: mariadb:10.6
    image: mariadb:10.4
    container_name: cloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /home/web/docker/cloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=!super_secret_password!
      - MYSQL_PASSWORD=!secret_password!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - proxy
    ports:
      - 3306:3306

  nextcloud_template:
    image: nextcloud:26
    container_name: cloud_template
    restart: always
    ports:
      - 8000:80
#    links:
#      - db
    volumes:
      - /home/web/docker/cloud_template/data:/var/www/html
#    environment:
#      - MYSQL_PASSWORD=UrFrYA3zv0
#      - MYSQL_DATABASE=nextcloud
#      - MYSQL_USER=nextcloud
#      - MYSQL_HOST=db
#      - TRUSTED_PROXIES=192.168.178.0
#      - TRUSTED_PROXIES=192.168.1.0
    networks:
      - proxy

  nextcloud:
    image: nextcloud:26
    container_name: cloud
    restart: always
    ports:
      - 10000:80
    links:
      - db
    volumes:
      - /home/web/docker/cloud/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=!secret_password!
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - TRUSTED_PROXIES=192.168.178.0
      - TRUSTED_PROXIES=192.168.1.0
    networks:
      - proxy

networks:
  proxy:
    external: true
